security:
    providers:
        mysql:
            entity:
                class: App\Entity\Utilisateurs
                property: numero
    encoders:
        App\Entity\Utilisateurs:
            algorithm: bcrypt
            encode_as_base64: false
            iterations: 13
            
    firewalls:
        main:
            anonymous: true
            pattern: ^/
            form_login:
                login_path: login
                
                check_path: login
                default_target_path: accueil
            provider: mysql
            logout:
                path:   /logout
                target: /
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN}